version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "15:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps
    groups:
      python-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "16:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
