"""Pinned Chipyard subsystem integration for physical-compute-mmio/v1.

The generated Scala enters the current Chipyard `DigitalTop` through the
upstream subsystem-injector API. It does not patch the upstream top-level class.
The admitted v0.11 configuration deliberately retains the internal loopback
fallback so subsystem elaboration cannot be mistaken for an external cartridge
or physical-compute result.
"""

from __future__ import annotations

from hashlib import sha256
from typing import Any

from .mmio_abi import (
    CAPABILITY_BITS,
    COMMAND_BITS,
    STATUS_BITS,
    bit_mask,
    build_mmio_abi,
    canonical_json,
)
from .physical_constants import PHYSICAL_COMPUTE_MMIO_V1, PORTABLE_BINDING

CHIPYARD_INTEGRATION_SCHEMA_VERSION = (
    "ahead.chipyard-physical-compute-integration/v0.2"
)
CHIPYARD_REPOSITORY = "ucb-bar/chipyard"
CHIPYARD_COMMIT = "e27c6561c0066c1f60bf4eb4885a38391c850ac0"
CHIPYARD_CONFIG_PACKAGE = "chipyard.physicalcompute"
CHIPYARD_CONFIG_CLASS = "PhysicalComputeRocketConfig"
CHIPYARD_SCALA_INSTALL_PATH = (
    "generators/chipyard/src/main/scala/physicalcompute/PhysicalCompute.scala"
)
# The pinned upstream GCD TileLink example uses 0x4000. The previous
# 0x02000000 default collided with the Rocket CLINT window during elaboration.
DEFAULT_BASE_ADDRESS = 0x0000_4000
ELABORATION_WITNESS_NAME = "ahead_physical_compute_elaboration_witness"
ELABORATION_WITNESS_VALUE = 0xA11E_CAFE

CHIPYARD_SOURCE_WITNESSES: dict[str, dict[str, Any]] = {
    "generators/chipyard/src/main/scala/example/GCD.scala": {
        "blob_sha": "f1579822bc7bacab7dcdfac742034266ddea012b",
        "required_patterns": [
            "ClockSinkDomain",
            "TLRegisterNode",
            "RegField",
            "TLInwardClockCrossingHelper",
            "TLFragmenter",
            "BaseSubsystem",
            "PBUS",
        ],
    },
    "generators/chipyard/src/main/scala/config/RocketConfigs.scala": {
        "blob_sha": "b0cea36c66eab808d5abc67c1590832cca1d579d",
        "required_patterns": [
            "class RocketConfig",
            "WithNHugeCores(1)",
            "chipyard.config.AbstractConfig",
        ],
    },
    "generators/chipyard/src/main/scala/DigitalTop.scala": {
        "blob_sha": "0f1ee688b5f5977f4679a900767da07390a3711b",
        "required_patterns": [
            "class DigitalTop",
            "testchipip.soc.CanHaveSubsystemInjectors",
            "class DigitalTopModule",
        ],
    },
    "variables.mk": {
        "blob_sha": "a1de5294882ad5a577d9033d5180951b947d6057",
        "required_patterns": [
            "CONFIG_PACKAGE",
            "FIRRTL_FILE",
            "ANNO_FILE",
            "CHISEL_LOG_FILE",
        ],
    },
    # The repository-root build-setup.sh entry is a symlink. Witness the
    # regular script that the symlink executes so the path, blob identity,
    # required patterns, and bytes all describe the same upstream object.
    "scripts/build-setup.sh": {
        "blob_sha": "709fc4db6ea274094921a41de52a2ad6c7816fdb",
        "required_patterns": [
            "--use-lean-conda",
            "--skip-submodules",
            "--skip-toolchain",
            "--skip-precompile",
            "--skip-circt",
        ],
    },
}

CHIPYARD_SUBMODULE_WITNESSES: dict[str, list[str]] = {
    "generators/testchipip/src/main/scala/soc/SubsystemInjector.scala": [
        "abstract class SubsystemInjector",
        "case object SubsystemInjectorKey",
        "trait CanHaveSubsystemInjectors",
    ],
}

# Backward-compatible names for the original public source witness.
CHIPYARD_REFERENCE_REF = CHIPYARD_COMMIT
CHIPYARD_REFERENCE_PATH = "generators/chipyard/src/main/scala/example/GCD.scala"
CHIPYARD_REFERENCE_BLOB_SHA = CHIPYARD_SOURCE_WITNESSES[
    CHIPYARD_REFERENCE_PATH
]["blob_sha"]
CHIPYARD_REFERENCE_URL = (
    f"https://github.com/{CHIPYARD_REPOSITORY}/blob/{CHIPYARD_COMMIT}/"
    f"{CHIPYARD_REFERENCE_PATH}"
)


def _hex32(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08X}"


def _validate_base_address(base_address: int) -> None:
    if base_address < 0 or base_address % 0x1000:
        raise ValueError("Chipyard base address must be non-negative and 4 KiB aligned")


def render_chipyard_scala(*, base_address: int = DEFAULT_BASE_ADDRESS) -> str:
    _validate_base_address(base_address)
    off = PHYSICAL_COMPUTE_MMIO_V1
    cmd = {name: bit_mask(bit) for name, bit in COMMAND_BITS.items()}
    status = {name: bit_mask(bit) for name, bit in STATUS_BITS.items()}
    caps = {name: bit_mask(bit) for name, bit in CAPABILITY_BITS.items()}

    return f"""// Generated by ahead-rev-sim from {PORTABLE_BINDING}.
// Pinned Chipyard commit: {CHIPYARD_COMMIT}
// Entry path: testchipip.soc.SubsystemInjectorKey, without patching DigitalTop.
// Qualification: loopback-fallback subsystem candidate until pinned elaboration passes.
package {CHIPYARD_CONFIG_PACKAGE}

import chisel3._
import chisel3.util._
import freechips.rocketchip.prci._
import freechips.rocketchip.subsystem.PBUS
import org.chipsalliance.cde.config.{{Parameters, Field, Config}}
import freechips.rocketchip.diplomacy._
import freechips.rocketchip.regmapper.RegField
import freechips.rocketchip.tilelink._
import testchipip.soc.{{SubsystemInjector, SubsystemInjectorKey}}

case class PhysicalComputeParams(
  address: BigInt = BigInt("{base_address:X}", 16),
  loopbackFallback: Boolean = true)

case object PhysicalComputeKey extends Field[Option[PhysicalComputeParams]](None)

class PhysicalComputeTL(params: PhysicalComputeParams, beatBytes: Int)(implicit p: Parameters)
    extends ClockSinkDomain(ClockSinkParameters())(p) {{
  require(params.loopbackFallback,
    "The v0.11 Chipyard proof admits only the sealed loopback fallback configuration")

  val device = new SimpleDevice(
    "ahead-physical-compute",
    Seq("ahead,physical-compute-mmio-v1"))
  val node = TLRegisterNode(
    Seq(AddressSet(params.address, 4096 - 1)),
    device,
    "reg/control",
    beatBytes = beatBytes)

  override lazy val module = new PhysicalComputeImpl

  class PhysicalComputeImpl extends Impl {{
    withClockAndReset(clock, reset) {{
      val Identity = "h41504859".U(32.W)
      val Capabilities = "h{caps['software_fallback'] | caps['exact']:08X}".U(32.W)

      val CmdReset = "h{cmd['reset']:08X}".U(32.W)
      val CmdLoad = "h{cmd['load']:08X}".U(32.W)
      val CmdEvolve = "h{cmd['evolve']:08X}".U(32.W)
      val CmdRead = "h{cmd['read']:08X}".U(32.W)
      val CmdCapture = "h{cmd['capture']:08X}".U(32.W)
      val SupportedCommands = CmdReset | CmdLoad | CmdEvolve | CmdRead | CmdCapture

      val StatusReady = "h{status['ready']:08X}".U(32.W)
      val StatusBusy = "h{status['busy']:08X}".U(32.W)
      val StatusDone = "h{status['done']:08X}".U(32.W)
      val StatusRefused = "h{status['refused']:08X}".U(32.W)
      val StatusFault = "h{status['fault']:08X}".U(32.W)
      val StatusReceiptValid = "h{status['receipt_valid']:08X}".U(32.W)

      val command = RegInit(0.U(32.W)).suggestName("physical_compute_command")
      val statusReg = RegInit(StatusReady).suggestName("physical_compute_status")
      val descriptorPtr = RegInit(0.U(64.W)).suggestName("physical_compute_descriptor_ptr")
      val inputQueuePtr = RegInit(0.U(64.W)).suggestName("physical_compute_input_ptr")
      val outputQueuePtr = RegInit(0.U(64.W)).suggestName("physical_compute_output_ptr")
      val receiptPtr = RegInit(0.U(64.W)).suggestName("physical_compute_receipt_ptr")
      val commandValid = RegInit(false.B).suggestName("physical_compute_command_valid")

      val elaborationWitness = WireDefault(
        "h{ELABORATION_WITNESS_VALUE:08X}".U(32.W))
        .suggestName("{ELABORATION_WITNESS_NAME}")
      dontTouch(elaborationWitness)
      dontTouch(statusReg)

      val busy = (statusReg & StatusBusy) =/= 0.U

      val commandWrite = Wire(Decoupled(UInt(32.W)))
      val descriptorLoWrite = Wire(Decoupled(UInt(32.W)))
      val descriptorHiWrite = Wire(Decoupled(UInt(32.W)))
      val inputLoWrite = Wire(Decoupled(UInt(32.W)))
      val inputHiWrite = Wire(Decoupled(UInt(32.W)))
      val outputLoWrite = Wire(Decoupled(UInt(32.W)))
      val outputHiWrite = Wire(Decoupled(UInt(32.W)))
      val receiptLoWrite = Wire(Decoupled(UInt(32.W)))
      val receiptHiWrite = Wire(Decoupled(UInt(32.W)))
      val doorbell = Wire(Decoupled(UInt(32.W)))

      Seq(
        commandWrite,
        descriptorLoWrite,
        descriptorHiWrite,
        inputLoWrite,
        inputHiWrite,
        outputLoWrite,
        outputHiWrite,
        receiptLoWrite,
        receiptHiWrite,
        doorbell).foreach(_.ready := !busy)

      when(commandWrite.fire) {{ command := commandWrite.bits }}
      when(descriptorLoWrite.fire) {{
        descriptorPtr := Cat(descriptorPtr(63, 32), descriptorLoWrite.bits)
      }}
      when(descriptorHiWrite.fire) {{
        descriptorPtr := Cat(descriptorHiWrite.bits, descriptorPtr(31, 0))
      }}
      when(inputLoWrite.fire) {{
        inputQueuePtr := Cat(inputQueuePtr(63, 32), inputLoWrite.bits)
      }}
      when(inputHiWrite.fire) {{
        inputQueuePtr := Cat(inputHiWrite.bits, inputQueuePtr(31, 0))
      }}
      when(outputLoWrite.fire) {{
        outputQueuePtr := Cat(outputQueuePtr(63, 32), outputLoWrite.bits)
      }}
      when(outputHiWrite.fire) {{
        outputQueuePtr := Cat(outputHiWrite.bits, outputQueuePtr(31, 0))
      }}
      when(receiptLoWrite.fire) {{
        receiptPtr := Cat(receiptPtr(63, 32), receiptLoWrite.bits)
      }}
      when(receiptHiWrite.fire) {{
        receiptPtr := Cat(receiptHiWrite.bits, receiptPtr(31, 0))
      }}

      val oneHotSupported = command.orR && PopCount(command) === 1.U &&
        ((command & ~SupportedCommands) === 0.U)
      val pointersReady = MuxLookup(command, false.B)(Seq(
        CmdReset -> true.B,
        CmdLoad -> (descriptorPtr.orR && inputQueuePtr.orR),
        CmdEvolve -> (inputQueuePtr.orR && outputQueuePtr.orR),
        CmdRead -> outputQueuePtr.orR,
        CmdCapture -> receiptPtr.orR))

      when(doorbell.fire) {{
        when(oneHotSupported && pointersReady) {{
          statusReg := StatusBusy
          commandValid := true.B
        }}.otherwise {{
          statusReg := StatusReady | StatusRefused
          commandValid := false.B
        }}
      }}

      val loopbackAccepted = commandValid
      val loopbackDone = RegNext(loopbackAccepted, false.B)
      when(commandValid) {{ commandValid := false.B }}
      when(busy && loopbackDone) {{
        statusReg := StatusReady | StatusDone | StatusReceiptValid
        commandValid := false.B
      }}

      node.regmap(
        0x{off['identity']:02X} -> Seq(RegField.r(32, Identity)),
        0x{off['capabilities']:02X} -> Seq(RegField.r(32, Capabilities)),
        0x{off['command']:02X} -> Seq(RegField(32, command, commandWrite)),
        0x{off['status']:02X} -> Seq(RegField.r(32, statusReg)),
        0x{off['descriptor_ptr_lo']:02X} -> Seq(
          RegField(32, descriptorPtr(31, 0), descriptorLoWrite)),
        0x{off['descriptor_ptr_hi']:02X} -> Seq(
          RegField(32, descriptorPtr(63, 32), descriptorHiWrite)),
        0x{off['input_queue_ptr_lo']:02X} -> Seq(
          RegField(32, inputQueuePtr(31, 0), inputLoWrite)),
        0x{off['input_queue_ptr_hi']:02X} -> Seq(
          RegField(32, inputQueuePtr(63, 32), inputHiWrite)),
        0x{off['output_queue_ptr_lo']:02X} -> Seq(
          RegField(32, outputQueuePtr(31, 0), outputLoWrite)),
        0x{off['output_queue_ptr_hi']:02X} -> Seq(
          RegField(32, outputQueuePtr(63, 32), outputHiWrite)),
        0x{off['receipt_ptr_lo']:02X} -> Seq(
          RegField(32, receiptPtr(31, 0), receiptLoWrite)),
        0x{off['receipt_ptr_hi']:02X} -> Seq(
          RegField(32, receiptPtr(63, 32), receiptHiWrite)),
        0x{off['doorbell']:02X} -> Seq(RegField.w(32, doorbell)))
    }}
  }}
}}

case object PhysicalComputeInjector extends SubsystemInjector((p, baseSubsystem) => {{
  p(PhysicalComputeKey).foreach {{ params =>
    implicit val q: Parameters = p
    val pbus = baseSubsystem.locateTLBusWrapper(PBUS)
    val peripheral = LazyModule(new PhysicalComputeTL(params, pbus.beatBytes)(p))
    peripheral.clockNode := pbus.fixedClockNode
    pbus.coupleTo("physical_compute") {{
      TLInwardClockCrossingHelper(
        "physical_compute_crossing",
        peripheral,
        peripheral.node)(SynchronousCrossing()) :=
      TLFragmenter(pbus.beatBytes, pbus.blockBytes) := _
    }}
  }}
}})

class WithPhysicalCompute(
  address: BigInt = BigInt("{base_address:X}", 16),
  loopbackFallback: Boolean = true)
    extends Config((site, here, up) => {{
      case PhysicalComputeKey => Some(
        PhysicalComputeParams(address, loopbackFallback))
      case SubsystemInjectorKey =>
        up(SubsystemInjectorKey) + PhysicalComputeInjector
    }})

class {CHIPYARD_CONFIG_CLASS} extends Config(
  new WithPhysicalCompute(
    address = BigInt("{base_address:X}", 16),
    loopbackFallback = true) ++
  new freechips.rocketchip.rocket.WithNHugeCores(1) ++
  new chipyard.config.AbstractConfig)
"""


def render_baremetal_smoke(*, base_address: int = DEFAULT_BASE_ADDRESS) -> str:
    _validate_base_address(base_address)
    off = PHYSICAL_COMPUTE_MMIO_V1
    cmd = {name: bit_mask(bit) for name, bit in COMMAND_BITS.items()}
    status = {name: bit_mask(bit) for name, bit in STATUS_BITS.items()}
    return f"""/* Generated lifecycle smoke for {PORTABLE_BINDING}. */
#include <stdint.h>
#include <stddef.h>

#define PHYS_BASE UINT64_C(0x{base_address:08X})
#define REG32(offset) (*(volatile uint32_t *)(uintptr_t)(PHYS_BASE + (offset)))

#define REG_IDENTITY 0x{off['identity']:02X}u
#define REG_CAPABILITIES 0x{off['capabilities']:02X}u
#define REG_COMMAND 0x{off['command']:02X}u
#define REG_STATUS 0x{off['status']:02X}u
#define REG_DESCRIPTOR_LO 0x{off['descriptor_ptr_lo']:02X}u
#define REG_DESCRIPTOR_HI 0x{off['descriptor_ptr_hi']:02X}u
#define REG_INPUT_LO 0x{off['input_queue_ptr_lo']:02X}u
#define REG_INPUT_HI 0x{off['input_queue_ptr_hi']:02X}u
#define REG_OUTPUT_LO 0x{off['output_queue_ptr_lo']:02X}u
#define REG_OUTPUT_HI 0x{off['output_queue_ptr_hi']:02X}u
#define REG_RECEIPT_LO 0x{off['receipt_ptr_lo']:02X}u
#define REG_RECEIPT_HI 0x{off['receipt_ptr_hi']:02X}u
#define REG_DOORBELL 0x{off['doorbell']:02X}u

#define CMD_RESET UINT32_C({_hex32(cmd['reset'])})
#define CMD_LOAD UINT32_C({_hex32(cmd['load'])})
#define CMD_READ UINT32_C({_hex32(cmd['read'])})

#define STATUS_READY UINT32_C({_hex32(status['ready'])})
#define STATUS_BUSY UINT32_C({_hex32(status['busy'])})
#define STATUS_DONE UINT32_C({_hex32(status['done'])})
#define STATUS_REFUSED UINT32_C({_hex32(status['refused'])})
#define STATUS_FAULT UINT32_C({_hex32(status['fault'])})
#define STATUS_RECEIPT_VALID UINT32_C({_hex32(status['receipt_valid'])})

static uint32_t descriptor_words[16] __attribute__((aligned(64)));
static uint32_t input_words[16] __attribute__((aligned(64)));
static uint32_t output_words[16] __attribute__((aligned(64)));
static uint32_t receipt_words[32] __attribute__((aligned(64)));

static void write_ptr(uint32_t lo_offset, uint32_t hi_offset, uintptr_t value) {{
    REG32(lo_offset) = (uint32_t)value;
    REG32(hi_offset) = (uint32_t)(((uint64_t)value) >> 32);
}}

static uint32_t wait_terminal(uint32_t limit) {{
    while (limit-- != 0) {{
        uint32_t status = REG32(REG_STATUS);
        if ((status & (STATUS_DONE | STATUS_REFUSED | STATUS_FAULT)) != 0) {{
            return status;
        }}
    }}
    return 0;
}}

int main(void) {{
    if (REG32(REG_IDENTITY) != UINT32_C(0x41504859)) return 1;

    REG32(REG_COMMAND) = CMD_RESET | CMD_READ;
    REG32(REG_DOORBELL) = 1;
    uint32_t status = wait_terminal(1024);
    if ((status & STATUS_REFUSED) == 0) return 2;

    REG32(REG_COMMAND) = CMD_RESET;
    REG32(REG_DOORBELL) = 1;
    status = wait_terminal(1024);
    if ((status & (STATUS_DONE | STATUS_RECEIPT_VALID)) !=
        (STATUS_DONE | STATUS_RECEIPT_VALID)) return 3;

    write_ptr(REG_DESCRIPTOR_LO, REG_DESCRIPTOR_HI, (uintptr_t)descriptor_words);
    write_ptr(REG_INPUT_LO, REG_INPUT_HI, (uintptr_t)input_words);
    write_ptr(REG_OUTPUT_LO, REG_OUTPUT_HI, (uintptr_t)output_words);
    write_ptr(REG_RECEIPT_LO, REG_RECEIPT_HI, (uintptr_t)receipt_words);

    REG32(REG_COMMAND) = CMD_LOAD;
    REG32(REG_DOORBELL) = 1;
    status = wait_terminal(1024);
    if ((status & STATUS_DONE) == 0) return 4;
    if ((status & STATUS_RECEIPT_VALID) == 0) return 5;
    if ((status & STATUS_BUSY) != 0) return 6;
    if ((status & STATUS_READY) == 0) return 7;

    return 0;
}}
"""


def _artifact_record(content: str) -> dict[str, Any]:
    payload = content.encode("utf-8")
    return {"sha256": sha256(payload).hexdigest(), "bytes": len(payload)}


def build_chipyard_manifest(*, base_address: int = DEFAULT_BASE_ADDRESS) -> dict[str, Any]:
    _validate_base_address(base_address)
    scala = render_chipyard_scala(base_address=base_address)
    smoke = render_baremetal_smoke(base_address=base_address)
    abi = build_mmio_abi()
    payload: dict[str, Any] = {
        "schema_version": CHIPYARD_INTEGRATION_SCHEMA_VERSION,
        "artifact_type": "chipyard_physical_compute_injector_bundle",
        "portable_binding": PORTABLE_BINDING,
        "base_address": base_address,
        "chipyard_source_contract": {
            "repository": CHIPYARD_REPOSITORY,
            "commit": CHIPYARD_COMMIT,
            "source_witnesses": CHIPYARD_SOURCE_WITNESSES,
            "submodule_witnesses": CHIPYARD_SUBMODULE_WITNESSES,
        },
        "integration": {
            "scala_install_path": CHIPYARD_SCALA_INSTALL_PATH,
            "config_package": CHIPYARD_CONFIG_PACKAGE,
            "config_class": CHIPYARD_CONFIG_CLASS,
            "entry_api": "testchipip.soc.SubsystemInjectorKey",
            "patches_digital_top": False,
            "loopback_fallback": True,
            "elaboration_witness_name": ELABORATION_WITNESS_NAME,
            "elaboration_witness_value": ELABORATION_WITNESS_VALUE,
        },
        "abi_sha256": abi["abi_sha256"],
        "generated_artifacts": {
            "PhysicalCompute.scala": _artifact_record(scala),
            "physical_compute_smoke.c": _artifact_record(smoke),
        },
        "qualification": {
            "status": "pinned_injector_bundle_unelaborated",
            "subsystem_elaboration_allowed": False,
            "physical_claim_allowed": False,
            "blockers": [
                "CHIPYARD_SUBSYSTEM_ELABORATION_UNRUN",
                "CHIPYARD_RTL_SIMULATION_UNRUN",
                "CHIPYARD_EXTERNAL_CARTRIDGE_BINDING_UNRUN",
                "RISC_V_BINARY_BUILD_UNRUN",
                "TARGET_TRACE_UNOBSERVED",
                "FPGA_OR_SILICON_EXECUTION_UNRUN",
                "PHYSICAL_SUBSTRATE_UNMEASURED",
                "COMPLETE_SYSTEM_EVP_UNMEASURED",
            ],
        },
        "claim_boundary": (
            "The bundle pins the upstream Chipyard commit, enters DigitalTop through "
            "the official subsystem-injector API, preserves the loopback fallback, "
            "and supplies a TileLink peripheral and bare-metal fixture. It does not "
            "establish Chipyard elaboration, Chipyard RTL simulation, an external "
            "cartridge binding, RISC-V workload execution, FPGA or silicon behavior, "
            "physical work, measured EVP, fabrication, or independent acceptance."
        ),
        "control_question": (
            "Can the physical-compute MMIO control plane elaborate inside the exact "
            "Chipyard subsystem through an upstream injector without patching "
            "DigitalTop or transferring workload and fallback authority to Chipyard?"
        ),
    }
    payload["manifest_sha256"] = sha256(
        canonical_json(payload).encode("utf-8")
    ).hexdigest()
    return payload
