"""Generated Chipyard TileLink integration for physical-compute-mmio/v1.

The source contract is pinned to the current public Chipyard MMIO example API.
Generated Scala is an integration candidate until it is elaborated and simulated
inside the pinned Chipyard checkout.
"""

from __future__ import annotations

from hashlib import sha256
import json
from pathlib import Path
from typing import Any

from .mmio_abi import (
    CAPABILITY_BITS,
    COMMAND_BITS,
    STATUS_BITS,
    bit_mask,
    build_mmio_abi,
    canonical_json,
)
from .physical_constants import PHYSICAL_COMPUTE_MMIO_V1, PORTABLE_BINDING

CHIPYARD_INTEGRATION_SCHEMA_VERSION = "ahead.chipyard-physical-compute-integration/v0.1"
CHIPYARD_REPOSITORY = "ucb-bar/chipyard"
CHIPYARD_REFERENCE_REF = "main"
CHIPYARD_REFERENCE_PATH = "generators/chipyard/src/main/scala/example/GCD.scala"
CHIPYARD_REFERENCE_BLOB_SHA = "f1579822bc7bacab7dcdfac742034266ddea012b"
CHIPYARD_REFERENCE_URL = (
    "https://github.com/ucb-bar/chipyard/blob/main/"
    "generators/chipyard/src/main/scala/example/GCD.scala"
)
DEFAULT_BASE_ADDRESS = 0x0200_0000


def _hex32(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08X}"


def render_chipyard_scala(*, base_address: int = DEFAULT_BASE_ADDRESS) -> str:
    if base_address < 0 or base_address % 0x1000:
        raise ValueError("Chipyard base address must be non-negative and 4 KiB aligned")

    off = PHYSICAL_COMPUTE_MMIO_V1
    cmd = {name: bit_mask(bit) for name, bit in COMMAND_BITS.items()}
    status = {name: bit_mask(bit) for name, bit in STATUS_BITS.items()}
    caps = {name: bit_mask(bit) for name, bit in CAPABILITY_BITS.items()}

    return f"""// Generated by ahead-rev-sim from {PORTABLE_BINDING}.
// Chipyard source contract: {CHIPYARD_REFERENCE_BLOB_SHA}
// Qualification: source-generated candidate; Chipyard elaboration and RTL simulation remain open.
package chipyard.physicalcompute

import chisel3._
import chisel3.util._
import freechips.rocketchip.prci._
import freechips.rocketchip.subsystem.{{BaseSubsystem, PBUS}}
import org.chipsalliance.cde.config.{{Parameters, Field, Config}}
import freechips.rocketchip.diplomacy._
import freechips.rocketchip.regmapper.RegField
import freechips.rocketchip.tilelink._

case class PhysicalComputeParams(
  address: BigInt = BigInt("{base_address:X}", 16),
  loopbackFallback: Boolean = true
)

case object PhysicalComputeKey extends Field[Option[PhysicalComputeParams]](None)

class PhysicalComputeDeviceIO extends Bundle {{
  val command_valid = Output(Bool())
  val command_ready = Input(Bool())
  val command = Output(UInt(32.W))
  val descriptor_ptr = Output(UInt(64.W))
  val input_queue_ptr = Output(UInt(64.W))
  val output_queue_ptr = Output(UInt(64.W))
  val receipt_ptr = Output(UInt(64.W))
  val command_done = Input(Bool())
  val command_refused = Input(Bool())
  val command_fault = Input(Bool())
  val receipt_valid = Input(Bool())
  val fallback_used = Output(Bool())
}}

trait HasPhysicalComputeDeviceIO {{
  def io: PhysicalComputeDeviceIO
}}

class PhysicalComputeTL(params: PhysicalComputeParams, beatBytes: Int)(implicit p: Parameters)
    extends ClockSinkDomain(ClockSinkParameters())(p) {{
  val device = new SimpleDevice("ahead-physical-compute", Seq("ahead,physical-compute-mmio-v1"))
  val node = TLRegisterNode(
    Seq(AddressSet(params.address, 4096 - 1)),
    device,
    "reg/control",
    beatBytes = beatBytes)

  override lazy val module = new PhysicalComputeImpl

  class PhysicalComputeImpl extends Impl with HasPhysicalComputeDeviceIO {{
    val io = IO(new PhysicalComputeDeviceIO)

    withClockAndReset(clock, reset) {{
      val Identity = "h41504859".U(32.W)
      val Capabilities = "h{caps['software_fallback'] | caps['exact']:08X}".U(32.W)

      val CmdReset = "h{cmd['reset']:08X}".U(32.W)
      val CmdLoad = "h{cmd['load']:08X}".U(32.W)
      val CmdEvolve = "h{cmd['evolve']:08X}".U(32.W)
      val CmdRead = "h{cmd['read']:08X}".U(32.W)
      val CmdCapture = "h{cmd['capture']:08X}".U(32.W)
      val SupportedCommands = CmdReset | CmdLoad | CmdEvolve | CmdRead | CmdCapture

      val StatusReady = "h{status['ready']:08X}".U(32.W)
      val StatusBusy = "h{status['busy']:08X}".U(32.W)
      val StatusDone = "h{status['done']:08X}".U(32.W)
      val StatusRefused = "h{status['refused']:08X}".U(32.W)
      val StatusFault = "h{status['fault']:08X}".U(32.W)
      val StatusReceiptValid = "h{status['receipt_valid']:08X}".U(32.W)

      val command = RegInit(0.U(32.W))
      val statusReg = RegInit(StatusReady)
      val descriptorPtr = RegInit(0.U(64.W))
      val inputQueuePtr = RegInit(0.U(64.W))
      val outputQueuePtr = RegInit(0.U(64.W))
      val receiptPtr = RegInit(0.U(64.W))
      val commandValid = RegInit(false.B)

      val busy = (statusReg & StatusBusy) =/= 0.U

      val commandWrite = Wire(Decoupled(UInt(32.W)))
      val descriptorLoWrite = Wire(Decoupled(UInt(32.W)))
      val descriptorHiWrite = Wire(Decoupled(UInt(32.W)))
      val inputLoWrite = Wire(Decoupled(UInt(32.W)))
      val inputHiWrite = Wire(Decoupled(UInt(32.W)))
      val outputLoWrite = Wire(Decoupled(UInt(32.W)))
      val outputHiWrite = Wire(Decoupled(UInt(32.W)))
      val receiptLoWrite = Wire(Decoupled(UInt(32.W)))
      val receiptHiWrite = Wire(Decoupled(UInt(32.W)))
      val doorbell = Wire(Decoupled(UInt(32.W)))

      Seq(
        commandWrite,
        descriptorLoWrite,
        descriptorHiWrite,
        inputLoWrite,
        inputHiWrite,
        outputLoWrite,
        outputHiWrite,
        receiptLoWrite,
        receiptHiWrite,
        doorbell).foreach(_.ready := !busy)

      when(commandWrite.fire) {{ command := commandWrite.bits }}
      when(descriptorLoWrite.fire) {{ descriptorPtr := Cat(descriptorPtr(63, 32), descriptorLoWrite.bits) }}
      when(descriptorHiWrite.fire) {{ descriptorPtr := Cat(descriptorHiWrite.bits, descriptorPtr(31, 0)) }}
      when(inputLoWrite.fire) {{ inputQueuePtr := Cat(inputQueuePtr(63, 32), inputLoWrite.bits) }}
      when(inputHiWrite.fire) {{ inputQueuePtr := Cat(inputHiWrite.bits, inputQueuePtr(31, 0)) }}
      when(outputLoWrite.fire) {{ outputQueuePtr := Cat(outputQueuePtr(63, 32), outputLoWrite.bits) }}
      when(outputHiWrite.fire) {{ outputQueuePtr := Cat(outputHiWrite.bits, outputQueuePtr(31, 0)) }}
      when(receiptLoWrite.fire) {{ receiptPtr := Cat(receiptPtr(63, 32), receiptLoWrite.bits) }}
      when(receiptHiWrite.fire) {{ receiptPtr := Cat(receiptHiWrite.bits, receiptPtr(31, 0)) }}

      val oneHotSupported = command.orR && PopCount(command) === 1.U &&
        ((command & ~SupportedCommands) === 0.U)
      val pointersReady = MuxLookup(command, false.B)(Seq(
        CmdReset -> true.B,
        CmdLoad -> (descriptorPtr.orR && inputQueuePtr.orR),
        CmdEvolve -> (inputQueuePtr.orR && outputQueuePtr.orR),
        CmdRead -> outputQueuePtr.orR,
        CmdCapture -> receiptPtr.orR))

      when(doorbell.fire) {{
        when(oneHotSupported && pointersReady) {{
          statusReg := StatusBusy
          commandValid := true.B
        }}.otherwise {{
          statusReg := StatusReady | StatusRefused
          commandValid := false.B
        }}
      }}

      val loopbackAccepted = if (params.loopbackFallback) commandValid else false.B
      val loopbackDone = RegNext(loopbackAccepted, false.B)
      val observedReady = if (params.loopbackFallback) true.B else io.command_ready
      val observedDone = if (params.loopbackFallback) loopbackDone else io.command_done
      val observedRefused = if (params.loopbackFallback) false.B else io.command_refused
      val observedFault = if (params.loopbackFallback) false.B else io.command_fault
      val observedReceipt = if (params.loopbackFallback) loopbackDone else io.receipt_valid

      when(commandValid && observedReady) {{ commandValid := false.B }}
      when(busy && observedFault) {{
        statusReg := StatusReady | StatusFault | Mux(observedReceipt, StatusReceiptValid, 0.U)
        commandValid := false.B
      }}.elsewhen(busy && observedRefused) {{
        statusReg := StatusReady | StatusRefused | Mux(observedReceipt, StatusReceiptValid, 0.U)
        commandValid := false.B
      }}.elsewhen(busy && observedDone) {{
        statusReg := StatusReady | StatusDone | Mux(observedReceipt, StatusReceiptValid, 0.U)
        commandValid := false.B
      }}

      io.command_valid := commandValid
      io.command := command
      io.descriptor_ptr := descriptorPtr
      io.input_queue_ptr := inputQueuePtr
      io.output_queue_ptr := outputQueuePtr
      io.receipt_ptr := receiptPtr
      io.fallback_used := params.loopbackFallback.B

      node.regmap(
        0x{off['identity']:02X} -> Seq(RegField.r(32, Identity)),
        0x{off['capabilities']:02X} -> Seq(RegField.r(32, Capabilities)),
        0x{off['command']:02X} -> Seq(RegField(32, command, commandWrite)),
        0x{off['status']:02X} -> Seq(RegField.r(32, statusReg)),
        0x{off['descriptor_ptr_lo']:02X} -> Seq(RegField(32, descriptorPtr(31, 0), descriptorLoWrite)),
        0x{off['descriptor_ptr_hi']:02X} -> Seq(RegField(32, descriptorPtr(63, 32), descriptorHiWrite)),
        0x{off['input_queue_ptr_lo']:02X} -> Seq(RegField(32, inputQueuePtr(31, 0), inputLoWrite)),
        0x{off['input_queue_ptr_hi']:02X} -> Seq(RegField(32, inputQueuePtr(63, 32), inputHiWrite)),
        0x{off['output_queue_ptr_lo']:02X} -> Seq(RegField(32, outputQueuePtr(31, 0), outputLoWrite)),
        0x{off['output_queue_ptr_hi']:02X} -> Seq(RegField(32, outputQueuePtr(63, 32), outputHiWrite)),
        0x{off['receipt_ptr_lo']:02X} -> Seq(RegField(32, receiptPtr(31, 0), receiptLoWrite)),
        0x{off['receipt_ptr_hi']:02X} -> Seq(RegField(32, receiptPtr(63, 32), receiptHiWrite)),
        0x{off['doorbell']:02X} -> Seq(RegField.w(32, doorbell)))
    }}
  }}
}}

trait CanHavePeripheryPhysicalCompute {{ this: BaseSubsystem =>
  private val pbus = locateTLBusWrapper(PBUS)

  val physicalCompute = p(PhysicalComputeKey).map {{ params =>
    val peripheral = LazyModule(new PhysicalComputeTL(params, pbus.beatBytes)(p))
    peripheral.clockNode := pbus.fixedClockNode
    pbus.coupleTo("physical_compute") {{
      TLInwardClockCrossingHelper(
        "physical_compute_crossing",
        peripheral,
        peripheral.node)(SynchronousCrossing()) :=
      TLFragmenter(pbus.beatBytes, pbus.blockBytes) := _
    }}

    InModuleBody {{
      val port = IO(new PhysicalComputeDeviceIO).suggestName("physical_compute")
      port.command_valid := peripheral.module.io.command_valid
      peripheral.module.io.command_ready := port.command_ready
      port.command := peripheral.module.io.command
      port.descriptor_ptr := peripheral.module.io.descriptor_ptr
      port.input_queue_ptr := peripheral.module.io.input_queue_ptr
      port.output_queue_ptr := peripheral.module.io.output_queue_ptr
      port.receipt_ptr := peripheral.module.io.receipt_ptr
      peripheral.module.io.command_done := port.command_done
      peripheral.module.io.command_refused := port.command_refused
      peripheral.module.io.command_fault := port.command_fault
      peripheral.module.io.receipt_valid := port.receipt_valid
      port.fallback_used := peripheral.module.io.fallback_used
      port
    }}
  }}
}}

class WithPhysicalCompute(
  address: BigInt = BigInt("{base_address:X}", 16),
  loopbackFallback: Boolean = true)
    extends Config((site, here, up) => {{
      case PhysicalComputeKey => Some(PhysicalComputeParams(address, loopbackFallback))
    }})

// Add `with chipyard.physicalcompute.CanHavePeripheryPhysicalCompute` to DigitalTop.
// Compose `new WithPhysicalCompute() ++ new chipyard.config.AbstractConfig` in a target Config.
"""


def render_baremetal_smoke(*, base_address: int = DEFAULT_BASE_ADDRESS) -> str:
    if base_address < 0 or base_address % 0x1000:
        raise ValueError("Chipyard base address must be non-negative and 4 KiB aligned")
    off = PHYSICAL_COMPUTE_MMIO_V1
    cmd = {name: bit_mask(bit) for name, bit in COMMAND_BITS.items()}
    status = {name: bit_mask(bit) for name, bit in STATUS_BITS.items()}
    return f"""/* Generated lifecycle smoke for {PORTABLE_BINDING}. */
#include <stdint.h>
#include <stddef.h>

#define PHYS_BASE UINT64_C(0x{base_address:08X})
#define REG32(offset) (*(volatile uint32_t *)(uintptr_t)(PHYS_BASE + (offset)))

#define REG_IDENTITY 0x{off['identity']:02X}u
#define REG_CAPABILITIES 0x{off['capabilities']:02X}u
#define REG_COMMAND 0x{off['command']:02X}u
#define REG_STATUS 0x{off['status']:02X}u
#define REG_DESCRIPTOR_LO 0x{off['descriptor_ptr_lo']:02X}u
#define REG_DESCRIPTOR_HI 0x{off['descriptor_ptr_hi']:02X}u
#define REG_INPUT_LO 0x{off['input_queue_ptr_lo']:02X}u
#define REG_INPUT_HI 0x{off['input_queue_ptr_hi']:02X}u
#define REG_OUTPUT_LO 0x{off['output_queue_ptr_lo']:02X}u
#define REG_OUTPUT_HI 0x{off['output_queue_ptr_hi']:02X}u
#define REG_RECEIPT_LO 0x{off['receipt_ptr_lo']:02X}u
#define REG_RECEIPT_HI 0x{off['receipt_ptr_hi']:02X}u
#define REG_DOORBELL 0x{off['doorbell']:02X}u

#define CMD_RESET UINT32_C({_hex32(cmd['reset'])})
#define CMD_LOAD UINT32_C({_hex32(cmd['load'])})
#define CMD_READ UINT32_C({_hex32(cmd['read'])})

#define STATUS_READY UINT32_C({_hex32(status['ready'])})
#define STATUS_BUSY UINT32_C({_hex32(status['busy'])})
#define STATUS_DONE UINT32_C({_hex32(status['done'])})
#define STATUS_REFUSED UINT32_C({_hex32(status['refused'])})
#define STATUS_FAULT UINT32_C({_hex32(status['fault'])})
#define STATUS_RECEIPT_VALID UINT32_C({_hex32(status['receipt_valid'])})

static uint32_t descriptor_words[16] __attribute__((aligned(64)));
static uint32_t input_words[16] __attribute__((aligned(64)));
static uint32_t output_words[16] __attribute__((aligned(64)));
static uint32_t receipt_words[32] __attribute__((aligned(64)));

static void write_ptr(uint32_t lo_offset, uint32_t hi_offset, uintptr_t value) {{
    REG32(lo_offset) = (uint32_t)value;
    REG32(hi_offset) = (uint32_t)(((uint64_t)value) >> 32);
}}

static uint32_t wait_terminal(uint32_t limit) {{
    while (limit-- != 0) {{
        uint32_t status = REG32(REG_STATUS);
        if ((status & (STATUS_DONE | STATUS_REFUSED | STATUS_FAULT)) != 0) {{
            return status;
        }}
    }}
    return 0;
}}

int main(void) {{
    if (REG32(REG_IDENTITY) != UINT32_C(0x41504859)) return 1;

    /* Two command bits must be refused rather than interpreted permissively. */
    REG32(REG_COMMAND) = CMD_RESET | CMD_READ;
    REG32(REG_DOORBELL) = 1;
    uint32_t status = wait_terminal(1024);
    if ((status & STATUS_REFUSED) == 0) return 2;

    /* The loopback fallback closes the command and receipt lifecycle only. */
    REG32(REG_COMMAND) = CMD_RESET;
    REG32(REG_DOORBELL) = 1;
    status = wait_terminal(1024);
    if ((status & (STATUS_DONE | STATUS_RECEIPT_VALID)) !=
        (STATUS_DONE | STATUS_RECEIPT_VALID)) return 3;

    write_ptr(REG_DESCRIPTOR_LO, REG_DESCRIPTOR_HI, (uintptr_t)descriptor_words);
    write_ptr(REG_INPUT_LO, REG_INPUT_HI, (uintptr_t)input_words);
    write_ptr(REG_OUTPUT_LO, REG_OUTPUT_HI, (uintptr_t)output_words);
    write_ptr(REG_RECEIPT_LO, REG_RECEIPT_HI, (uintptr_t)receipt_words);

    REG32(REG_COMMAND) = CMD_LOAD;
    REG32(REG_DOORBELL) = 1;
    status = wait_terminal(1024);
    if ((status & STATUS_DONE) == 0) return 4;
    if ((status & STATUS_RECEIPT_VALID) == 0) return 5;
    if ((status & STATUS_BUSY) != 0) return 6;
    if ((status & STATUS_READY) == 0) return 7;

    return 0;
}}
"""


def build_chipyard_manifest(*, base_address: int = DEFAULT_BASE_ADDRESS) -> dict[str, Any]:
    scala = render_chipyard_scala(base_address=base_address)
    smoke = render_baremetal_smoke(base_address=base_address)
    abi = build_mmio_abi()
    payload: dict[str, Any] = {
        "schema_version": CHIPYARD_INTEGRATION_SCHEMA_VERSION,
        "artifact_type": "chipyard_physical_compute_integration",
        "portable_binding": PORTABLE_BINDING,
        "base_address": base_address,
        "chipyard_source_contract": {
            "repository": CHIPYARD_REPOSITORY,
            "ref": CHIPYARD_REFERENCE_REF,
            "path": CHIPYARD_REFERENCE_PATH,
            "blob_sha": CHIPYARD_REFERENCE_BLOB_SHA,
            "url": CHIPYARD_REFERENCE_URL,
            "api_patterns": [
                "ClockSinkDomain",
                "TLRegisterNode",
                "RegField",
                "TLInwardClockCrossingHelper",
                "TLFragmenter",
                "BaseSubsystem",
                "PBUS",
            ],
        },
        "abi_sha256": abi["abi_sha256"],
        "generated_artifacts": {
            "PhysicalCompute.scala": sha256(scala.encode("utf-8")).hexdigest(),
            "physical_compute_smoke.c": sha256(smoke.encode("utf-8")).hexdigest(),
        },
        "qualification": {
            "status": "source_generated_unqualified",
            "physical_claim_allowed": False,
            "blockers": [
                "CHIPYARD_CHECKOUT_NOT_PINNED_TO_COMMIT",
                "CHIPYARD_ELABORATION_UNRUN",
                "RISC_V_BINARY_BUILD_UNRUN",
                "RTL_SIMULATION_UNRUN",
                "TARGET_TRACE_UNOBSERVED",
                "PHYSICAL_EXECUTION_UNMEASURED",
            ],
        },
        "claim_boundary": (
            "The bundle binds the generated ABI to the current public Chipyard MMIO "
            "construction pattern and supplies a source-level TileLink peripheral and "
            "bare-metal lifecycle fixture. It does not establish Chipyard elaboration, "
            "RTL simulation, RISC-V target execution, physical work, energy, timing, "
            "thermal closure, occupied volume, or manufacturability."
        ),
    }
    payload["manifest_sha256"] = sha256(
        canonical_json(payload).encode("utf-8")
    ).hexdigest()
    return payload


def write_chipyard_bundle(
    output_dir: str | Path,
    *,
    base_address: int = DEFAULT_BASE_ADDRESS,
) -> dict[str, Path]:
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    outputs = {
        "scala": root / "PhysicalCompute.scala",
        "smoke": root / "physical_compute_smoke.c",
        "manifest": root / "chipyard-physical-compute-integration.json",
    }
    outputs["scala"].write_text(
        render_chipyard_scala(base_address=base_address), encoding="utf-8"
    )
    outputs["smoke"].write_text(
        render_baremetal_smoke(base_address=base_address), encoding="utf-8"
    )
    outputs["manifest"].write_text(
        json.dumps(
            build_chipyard_manifest(base_address=base_address),
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return outputs
